# Generated by Django 5.2.13 on 2026-05-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='maps_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Google Haritalar Linki'),
        ),
    ]
