# Generated by Django 5.2.13 on 2026-04-17 16:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Stok Kodu (SKU)')),
                ('description', models.TextField(blank=True, verbose_name='Ürün Açıklaması')),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toptan KG Fiyatı (TL)')),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Stok Miktarı (KG)')),
                ('minimum_order_quantity', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.10'))], verbose_name='Minimum Sipariş Miktarı (KG)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Satışta mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
            },
        ),
    ]
