# Generated by Django 5.2.13 on 2026-04-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_b2b',
            field=models.BooleanField(default=True, verbose_name='B2B Portalında Göster'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Halka Açık Vitrinde Göster'),
        ),
    ]
