# Generated by Django 5.2.13 on 2026-04-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_b2b_product_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='İşareti kaldırırsanız ürün sistemden tamamen gizlenir (Sezonu biten veya geçici olarak satışı durdurulan ürünler için kullanın).', verbose_name='1- Satışta mı? (Ana Şalter)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_b2b',
            field=models.BooleanField(default=True, help_text='Bu ürün, sisteme şifresiyle giriş yapan bayilerin sipariş ekranında (fiyatlarıyla birlikte) listelensin mi?', verbose_name='2- B2B Bayi Portalında Göster'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Bu ürün, siteye dışarıdan giren normal ziyaretçilerin genel kataloğunda (fiyat görünmeden) sergilensin mi?', verbose_name='3- Halka Açık Vitrinde Göster'),
        ),
    ]
