# Generated by Django 5.2.13 on 2026-05-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_price_publicly',
            field=models.BooleanField(default=False, verbose_name='Vitrin (Public) Kısmında Fiyatı Göster'),
        ),
    ]
