# Generated by Django 5.2.13 on 2026-05-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_show_price_publicly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='show_price_publicly',
        ),
        migrations.AddField(
            model_name='product',
            name='public_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Vitrin/Perakende Fiyatı (TL)'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_public_price',
            field=models.BooleanField(default=False, help_text="İşaretlenirse halka açık katalogda 'Vitrin/Perakende Fiyatı' görünür.", verbose_name='4- Vitrinde Fiyatı Göster'),
        ),
    ]
