# Generated by Django 5.2.13 on 2026-05-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_show_price_publicly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_whatsapp_order',
            field=models.BooleanField(default=True, help_text="Bu ürün için vitrinde 'WhatsApp ile Sipariş Ver' butonu görünsün mü?", verbose_name='5- WhatsApp Sipariş Butonu'),
        ),
    ]
