# Generated by Django 5.2.13 on 2026-05-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_step',
            field=models.IntegerField(choices=[(1, '1 kg (Standart)'), (3, '3 kg Katları'), (5, '5 kg Katları')], default=1, help_text="B2B kısmında bu ürünün kaçar kg'lık katlarla satılacağını belirler.", verbose_name='B2B Satış Katı (kg)'),
        ),
    ]
