# Generated by Django 5.2.13 on 2026-05-06 21:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_unit_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='minimum_order_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text="Lütfen üst kısımdaki 'B2B Satış Katı' ile uyumlu bir rakam girin (Örn: Katı 3 ise minimum 3, 6, 9; katı 5 ise 5, 10, 15 gibi).", max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.10'))], verbose_name='Minimum Sipariş Miktarı (KG)'),
        ),
    ]
