# Generated by Django 5.2.13 on 2026-05-07 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_minimum_order_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Kampanya Başlığı (Sadece Admin Görür)')),
                ('image', models.ImageField(upload_to='campaigns/%Y/%m/', verbose_name='Kampanya Görseli (Yatay Banner)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yayında mı?')),
                ('product', models.ForeignKey(blank=True, help_text='Müşteri görsele tıkladığında hangi ürüne gitsin?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Yönlendirilecek Ürün')),
            ],
            options={
                'verbose_name': "Kampanya Banner'ı",
                'verbose_name_plural': "Kampanya Banner'ları",
                'ordering': ['order', '-id'],
            },
        ),
    ]
