# Generated by Django 5.2.13 on 2026-05-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_campaign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['order', '-id'], 'verbose_name': 'Özel Bölüm / Kampanya', 'verbose_name_plural': 'Özel Bölümler / Kampanyalar'},
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='product',
        ),
        migrations.AddField(
            model_name='campaign',
            name='products',
            field=models.ManyToManyField(related_name='campaigns', to='products.product', verbose_name='Kampanyaya Dahil Ürünler'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns/%Y/%m/', verbose_name='Bölüm Banner Görseli (Opsiyonel)'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(help_text='Örn: En Sevilen Ürünler', max_length=150, verbose_name='Kampanya/Bölüm Başlığı'),
        ),
    ]
