# Generated by Django 5.2.13 on 2026-05-07 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_campaign_options_remove_campaign_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Slayt Başlığı (Sadece Admin Görür)')),
                ('image', models.ImageField(upload_to='hero/%Y/%m/', verbose_name='Hero Görseli (Tavsiye: 1920x530)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yayında mı?')),
                ('product', models.ForeignKey(blank=True, help_text='Eğer bir ürün seçerseniz, slayta tıklandığında o ürünün detayına gider.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Yönlendirilecek Ürün (Opsiyonel)')),
            ],
            options={
                'verbose_name': 'Hero Slaytı',
                'verbose_name_plural': 'Hero Slaytları',
                'ordering': ['order', '-id'],
            },
        ),
    ]
