# Generated by Django 5.2.13 on 2026-05-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_heroslide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroslide',
            name='product',
        ),
        migrations.AddField(
            model_name='heroslide',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Eğer ürün seçerseniz, slayta tıklandığında sayfa sadece o ürünleri listeleyecek şekilde filtrelenir.', related_name='hero_slides', to='products.product', verbose_name='Yönlendirilecek Ürünler (Opsiyonel)'),
        ),
    ]
