# Generated by Django 5.2.13 on 2026-05-08 22:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_heroslide_product_heroslide_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_step',
            field=models.DecimalField(choices=[(Decimal('0.5'), '0.5 kg (Yarım Kilo)'), (Decimal('1.0'), '1 kg (Standart)'), (Decimal('2.5'), '2.5 kg Katları'), (Decimal('3.0'), '3 kg Katları'), (Decimal('5.0'), '5 kg Katları'), (Decimal('10.0'), '10 kg Katları')], decimal_places=2, default=Decimal('1.0'), help_text="B2B kısmında bu ürünün kaçar kg'lık katlarla satılacağını belirler.", max_digits=5, verbose_name='B2B Satış Katı (kg)'),
        ),
    ]
