# Generated by Django 5.2.13 on 2026-05-08 23:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_product_minimum_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='minimum_order_quantity',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Lütfen üst kısımdaki 'B2B Satış Katı' ile tam bölünebilen uyumlu bir rakam girin. Örneğin satış katı 2.5 ise buraya 2.5, 5, 7.5, 10 gibi değerler girin.", max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.10'))], verbose_name='Minimum Sipariş Miktarı (KG)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_step',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text="Bu ürünün kaçar kg'lık katlarla satılacağını serbestçe yazabilirsiniz. Hangi sayıyı girerseniz ürün o şekilde artar. Örneğin 2.5 girerseniz 2.5, 5, 7.5 10 şeklinde artar.", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.10'))], verbose_name='B2B Satış Katı (kg)'),
        ),
    ]
